### ISSUE TITLE
GSP's remove threshold

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#205]
**Describe the bug**
in v1 of GSP data, the data was normalized by the capacity, this means we cant remove GSP's based on MW threshold

**To Reproduce**
Run prepare_ml_script with DEBUG as logger

**Expected behavior**
Only remove some GSPs

**Additional context**

**Comment by JackKelly** [comment]
After thinking some more about how we report our forecast skill, I think one of the most important quantities that ESO will want us to forecast is total _national_ PV generation.  Which I imagine we'd compute by predicting GSP-level PV for _every_ GSP; and adding up the forecasts for every GSP to get a number for national PV.  Which suggests that we probably _shouldn't_ throw away any GSPs with _any_ PV!  Because, if we throw away, say, 100 MW of GSPs, then our national PV forecast will always be biased too low by 100 MW :)  (But we probably _should_ ignore any GSPs with literally zero installed PV capacity).

**Comment by JackKelly** [comment]
As discussed just now:

For now, let's including all GSPs with any amount of PV.  (i.e. only filter out the GSPs with zero PV installed).

Then let's look to see if we get particularly high errors on some GSPs.

(Also, this issue is related to #303)

**Comment by JackKelly** [comment]
Related to PR #418

Maybe we can close this issue now, and leave #303 open?
