### ISSUE TITLE
Extend training to include dusk and dawn

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_dataset#608]
I noticed (after 1 day) that the trained model had a large error during 'dawn' and 'dusk'. 
This is perhaps due to training data does not include the 'dawn' and 'dusk'

However I can't find it in the code (nowcasting_dataset). It looks none of the [training example](https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-951/all?path=validation%2Fplot%2F&attribute=epoch_2_4)s are at night. So we must do this filtering somewhere. 
Is it perhaps done in the [pvoutput](https://github.com/openclimatefix/pvoutput) code 

@JackKelly , @jacobbieker can you remember this anyway. 

if we do fine where this filtering is done. Could I suggest +-2 from sunrise and sunset

**Comment by JackKelly** [comment]
I'm away from my pc right now but I think the filtering is done in the satellite data source, in the datetimes method.

And, yeah, I agree, we should include more nighttime data

**Comment by JackKelly** [comment]
And, when we get round to creating a dataset with a forecast horizon of up to 48 hours ahead (issue #609), we might want to completely drop the idea of filtering by "daylight" (because all examples will span 2 days, and because we need to create good forecasts for the transition to and from nighttime).
